import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import {Outfit,Roboto} from 'next/font/google'

// page imports
import Image from "next/image";
import Logo from "./navbar/Logo";
import Navbarlinks from "./navbar/Navbarlinks";
import ActionButton from "./navbar/ActionButtons";
import Footer from "./footer/Footer";

const outfit = Outfit({subsets:['latin']});
const roboto =Roboto({subsets:['latin'],weight:['100','300','400','500','700','900']});

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${outfit.className} ${roboto.className}  antialiased`}
      >
          {/* navbar */}
    <div className="flex justify-between items-center px-8 py-5 border-b-2 h-24">
    <div className="">
    <Logo/>
    </div>
    <div className="">
      <Navbarlinks/>
    </div>

    <div className="">
      <ActionButton/>
    </div>
    </div>
      {/*  navbar ends here*/}
        {children}
    {/* footer */}
    <div className="">
      <Footer/>
    </div>
      </body>
    </html>
  );
}
